### PR TITLE
fix parsePNodeStr openParser exception not handled

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Comment by Vindaar** [comment]
or is it `p`?

**Comment by bung87** [comment]
> or is it `p`?

what do mean?

**Comment by Vindaar** [comment]
> > or is it `p`?
> 
> what do mean?

It was a joke about the exceptionally descriptive PR + commit name `o` :rofl:

**Comment by haxscramper** [comment]
It means that more descriptive commit messages would be appreciated, though this fix is not that big anyway

**Comment by bung87** [comment]
oh, yeah I see that comment kind of funny. it's discussed so the commit message does not matters.

**Comment by Vindaar** [comment]
Sorry, I didn't want to start a discussion about this. 

I disagree though. It's fine for you + haxscramper *at this moment*. 
1. looking back at the git history in a few months you might have forgotten that context.
2. for people not familiar with any discussions it's nice to get some context. 

This is one of my big gripes with changes to the Nim compiler tbh. Often bug fixes are just a "fix issue number" without any comment about a why and in particular about *how* something is fixed on an abstract level. It makes for a very hostile experience getting into development as someone who doesn't yet understand everything in the person's head.

I'll be quiet now. :)

**Comment by bung87** [comment]
I thought this project is not widely used at this moment, just few people involved , I agree with you I'll at least provide one sentence information.

**Comment by haxscramper** [comment]
It is not fine by me either, but it is 23:30 here, and last thing I want now is to get on someones's nerves about wrong commit wording

**Pull request merged**
